### PR TITLE
quivr uses bramble crypto dependency, instead of node, DO NOT MERGE

### PR DESCRIPTION
**Pull request by nandotorterolo**
## Purpose
quivr uses bramble crypto dependency, instead of node

## Approach
use Brambl latest commit

## Testing
prepare PR ok

### CODE REVIEW

**Comment by nandotorterolo** [comment]
@DiademShoukralla do you know if quivr4s should use crypto library from Bramble:
I am having issues trying to use brambl from Node:
Quivr pull me an old version of cripto (Dion)

```
[info] compiling 1 Scala source to /home/fernando/topl/Bifrost/network-delayer/target/scala-2.13/classes ...
[error] stack trace is suppressed; run last tetraByteCodecs / update for the full output
[error] (tetraByteCodecs / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error]         * co.topl:crypto_2.13:2.0.0-alpha0-4-52a5050b-20230213-1746 (early-semver) is selected over 1.10.2
[error]             +- co.topl:tetra-byte-codecs_2.13:2.0.0-alpha0-4-52a5050b-20230213-1746 (depends on 2.0.0-alpha0-4-52a5050b-20230213-1746)
[error]             +- com.github.Topl:quivr4s:3bcc730                    (depends on 1.10.2)
[error] 
[error] 
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] Total time: 104 s (01:44), completed Feb 13, 2023, 5:48:43 PM
```

**Comment by DiademShoukralla** [comment]
Do we want quivr4s to use Brambl crypto?  I ask because I know quivr should not depend on Brambl (but am not sure since crypto will be a separate artifact than the rest of the SDK). I had opened a ticket before to decide what to do (what library to replace it with). See: https://topl.atlassian.net/browse/TSDK-243
Perhaps then if you are making this change you should assign yourself to the ticket. (+also I think you may want to double check the change doesnt break anything since the API might be a bit different)

**Comment by nandotorterolo** [comment]
https://toplprotocol.slack.com/archives/C01TBT00MTJ/p1676326623135229

**Comment by nandotorterolo** [comment]
TBD, reopen later

**Pull request closed without merging**
